"""Shared Agent abstractions."""

import asyncio
from dataclasses import dataclass
from typing import Any, Generic, TypeVar

from pydantic import BaseModel, Field

from app.agents.context_bus import PlanningContextBus


T = TypeVar("T")


class AgentTrace(BaseModel):
    """Observable metadata for one Agent step."""

    agent_name: str = Field(..., description="Agent name")
    prompt: str = Field(..., description="Role prompt")
    user_query: str = Field(..., description="Query sent to the Agent")
    tool_calls: list[str] = Field(default_factory=list, description="Tool calls")
    summary: str = Field(..., description="Short response summary")
    reasoning_summary: str = Field(
        default="",
        description="Concise, user-visible explanation of the Agent decision process",
    )
    agent_response: str = Field(default="", description="Role response generated by LLM")
    context: dict[str, Any] = Field(
        default_factory=dict,
        description="Request-scoped Context Bus summary for this Agent",
    )


@dataclass(frozen=True)
class AgentResult(Generic[T]):
    """Structured Agent output plus trace data."""

    data: T
    trace: AgentTrace


class BaseAgent:
    """Base class for role-specific Agents."""

    name: str = "base_agent"
    prompt_template: str = ""

    def __init__(
        self,
        amap_tools: Any | None = None,
        llm_service: Any | None = None,
        context_bus: PlanningContextBus | None = None,
    ) -> None:
        self.amap_tools = amap_tools
        self.llm_service = llm_service
        self.context_bus = context_bus

    def set_context_bus(self, context_bus: PlanningContextBus | None) -> None:
        self.context_bus = context_bus

    def context_summary(self) -> dict[str, Any]:
        if self.context_bus is None:
            return {}
        return self.context_bus.trace_summary_for(self.name)

    def render_prompt(self, **kwargs: object) -> str:
        return self.prompt_template.format(**kwargs)

    def toolset_summary(self) -> str:
        if self.amap_tools is None:
            return "No shared MCP toolset attached."
        return self.amap_tools.describe()

    async def build_agent_response(
        self,
        *,
        prompt: str,
        user_query: str,
        context: str,
        fallback: str,
    ) -> str:
        if self.llm_service is None:
            return fallback
        try:
            return await asyncio.wait_for(
                self.llm_service.generate_agent_reply(
                    agent_name=self.name,
                    system_prompt=prompt,
                    user_query=user_query,
                    context=context,
                    fallback=fallback,
                ),
                timeout=self.llm_service.settings.agent_response_timeout,
            )
        except asyncio.TimeoutError:
            return fallback
